version: '3.7'
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-production

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-production
    container_name: fastapi_app
    command: ["/code/docker/app.sh"]
    ports: [8000:8000]
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-production
    container_name: celery_app
    command: ["/code/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-production
    container_name: flower_app
    command: ["/code/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports: [8888:5555]
